### ISSUE TITLE
Add in some manual gc.collect()/torch.cuda.empty_cache() to the nodes

### ISSUE THREAD

**Issue by RandomGitUser321** [kijai/ComfyUI-LuminaWrapper#10]
I've tried various different comfyui settings like --lowvram and with or without the keep_model_loaded true/false and it seems like a chunk of vram stays permanently tied up. It's probably a comfyui thing.

I added:
```
if not keep_model_loaded:
    print("Offloading Lumina model...")
    model.to(offload_device)
    gc.collect()
    torch.cuda.empty_cache()
```
to the `LuminaGemmaTextEncode` and `LuminaGemmaTextEncode` classes, within `nodes.py`, and now they seem to work fine and properly flush the vram

EDIT: oh and you might need to `import gc` but I'd assume it might be loaded from somewhere else already.

Also, you might want to add some kind of cleanup like this for in the event that a user cancels the sampler early. It doesn't seem to free up the space again until you rerun it, which might cause issues on the gemma sampling step if a large chunk of vram is now being held up by the cache still in vram.

**Comment by kijai** [comment]
I don't really know how to handle the case of the cancel, comfy automatic model management seems to require using the comfy model patcher object and I don't know how to wrap custom models like this to it.

The rest I added in latest update.
