### ISSUE TITLE
Error occurred when executing LuminaT2ISampler:  index 5 is out of bounds for dimension 0 with size 4

### ISSUE THREAD

**Issue by Beamhi** [kijai/ComfyUI-LuminaWrapper#11]
I get this error if the row numbers are not the same:
Error occurred when executing LuminaT2ISampler:

index 5 is out of bounds for dimension 0 with size 4

**Comment by kijai** [comment]
Can you elaborate? The rows and columns need to form a grid, example from the original demo:
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/40791699/d5a2a718-a1e6-4699-9604-1d11ec39cf4d)

**Comment by Beamhi** [comment]
![CleanShot 2024-06-19 at 11 56 24@2x](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/121045060/258e162e-a015-473b-8d79-bed8fc1803a8)
think I get it now, couldn't get the horse though :)
