### ISSUE TITLE
Can find pre-built wheels build flash attention 2 for cuda 12.1

### ISSUE THREAD

**Issue by wardensc2** [kijai/ComfyUI-LuminaWrapper#13]
Hi Kijai

Can the link you provide for pre-builte wheels build of flash attention 2 (https://github.com/bdashore3/flash-attention/releases) only support cuda 12.2, I can't find cuda 12.1 version. Can you support us to find cuda 12.1 version or guide us to upgrade cuda from 12.1 to 12.2

Thank you so much

**Comment by kijai** [comment]
The one build for 12.2 should still work, minor versions can mismatch a bit usually.

**Comment by diodiogod** [comment]
I used the 12.2 and it worked.

**Comment by wardensc2** [comment]
I use 12.2 version and get error:

![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/77379748/fc077788-a087-42b3-9634-15e5d3b9f255)

This is my python and pytorch version: 

![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/77379748/66175b9a-333a-49da-8790-54de68e36be3)

I change to pre build wheel python 3.10 cuda 12.2 torch 2.3.1 and I can install successfully but so far my ComfyUI use SDP not Flash Attention: 

![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/77379748/3d5e7b43-6a2d-417e-a12c-7a1aecec0d58)

Can anyone help me ?

**Comment by kijai** [comment]
You need to use `python.exe -m pip install` even if you are in the right folder, only doing `pip install` there will still install it to your system's python env, not the portable's

**Comment by wardensc2** [comment]
Thank you. It's working now
