### ISSUE TITLE
How do I know I can use flash_attn?

### ISSUE THREAD

**Issue by caissonfiv** [kijai/ComfyUI-LuminaWrapper#17]
I find it still slow, flash attn is already installed.

**Comment by kijai** [comment]
Look for these lines in your console:
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/40791699/3a13c159-3655-4f81-8ae4-df0f189ea81b)

Also the Gemma node should say (in console) if it's using "flash_attention_2" or "sdpa"
