### ISSUE TITLE
Need Clarification for Installation

### ISSUE THREAD

**Issue by TCFrancis** [kijai/ComfyUI-LuminaWrapper#23]
Hi,
I need some clarification for installation.

1. I want to download the models with a browser in background.  My Last Try via the auto-download with the provided workflow-example were not successful.
Where do I put the models https://huggingface.co/Alpha-VLLM/Lumina-Next-SFT and https://huggingface.co/Alpha-VLLM/Lumina-Next-T2I? 
What exact folder structure?  
The info with insde "ComfyUI/models/lumina" is not enough, because the Models have the same file-names...

2. How to build and install the Flash-attn wheel?
I am trying to follow the guide at https://pypi.org/project/flash-attn/
and executing the command pip install flash-attn --no-build-isolation ? Is that correct, or am I missing something? Is the "--no-build-isolation"-Flag needed or too much?
Compiling seems to work right now. "Building Wheel" Do I need to move the file, or is it automatic installed after building? (I am using conda-env)
I have torch 2.3.1+cu121 and Python 3.11.9 (because of specific requirements of Comfy-3d-Pack). No prebuild wheel is matching...

3. What files exactly to download from (https://huggingface.co/google/gemma-2b. There are many...

**Comment by kijai** [comment]
1. Any idea how the autodownload fails, any errors? You want the whole folder with the non-ema version of the safetensors -file into `ComfyUI/models/lumina`, for example: 
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/40791699/4c345e33-50e2-46cd-85e9-b8a9000ae763)

2. If you build it with that command, it should install automatically. This wheel also should work, the minor cuda version mismatch isn't a big deal: https://github.com/bdashore3/flash-attention/releases/download/v2.5.9.post1/flash_attn-2.5.9.post1+cu122torch2.3.1cxx11abiFALSE-cp311-cp311-win_amd64.whl

3. Again the whole folder, besides the `gemma-2b.gguf` : 
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/40791699/17dd8e5a-f381-4649-959e-0d158ccaa345)

**Comment by TCFrancis** [comment]
1. Okay, thanks.  ...Lumina/Subfolder-Lumina-Next-SFT and ...lumina/Lumina-Next-T2I it is then :)
Download-Error in ComfyUI said something about file-difference. Size-mismatch or something...
2. Building wheel was succesful it and Successfully installed it :)
3. Thanks for making it clear :)
