### ISSUE TITLE
`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.

### ISSUE THREAD

**Issue by tiptinker** [kijai/ComfyUI-LuminaWrapper#29]
Gemma attention mode: flash_attention_2
`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.

**Comment by Philmar1986** [comment]
have the same problem

**Comment by MFaiqKhan** [comment]
this is a hugging face issue.
