### ISSUE TITLE
Suggestion..?

### ISSUE THREAD

**Issue by OliviaOliveiira** [kijai/ComfyUI-LuminaWrapper#3]
Hey!
I was wondering if you could write a wiki to get to know the model and the params a bit better, cause now I'm simply exploring it blindfolded + the official model page doesn't help much

**Comment by kijai** [comment]
I'm afraid we are in same boat in that regard, first time I even tried this was yesterday 😅

**Comment by OliviaOliveiira** [comment]
I see. Well, will look into ODE and stuff further then…:)
