### ISSUE TITLE
Which files?

### ISSUE THREAD

**Issue by DarkAlchy** [kijai/ComfyUI-LuminaWrapper#4]
I know you said we don't need the gguf, but what do we need?

![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/10561690/5df07d67-2cb6-43a3-8e21-b961dd96e011)

**Comment by kijai** [comment]
Almost everything else, besides the first two, to this folder: `ComfyUI\models\LLM\gemma-2b`

**Comment by DarkAlchy** [comment]
Thank you.
