### ISSUE TITLE
"Tokenizer class GemmaTokenizer does not exist or is not currently imported"

### ISSUE THREAD

**Issue by PeskyWabbit** [kijai/ComfyUI-LuminaWrapper#6]
currently getting this error when trying to run:
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/15241504/5e1acd09-155b-4603-9241-3261608feb1d)

My models/LLM/gemma-2b directory:
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/15241504/a5aed82c-aa92-4ff7-b495-32c2d79dd2e4)

my workflow:
![image](https://github.com/kijai/ComfyUI-LuminaWrapper/assets/15241504/6c5265f9-a194-4530-889a-40a9851a655a)

**Comment by PeskyWabbit** [comment]
I have refreshed and restarted comfyui since downloading gemma

**Comment by BenDes21** [comment]
noob question but where download the lumina sd model from here https://huggingface.co/Alpha-VLLM/Lumina-Next-SFT/tree/main and also where place the gemma model ? Thanks !

**Comment by diodiogod** [comment]
I had the same error. On comfyui manager go to the Pip install packages: -q -U transformers
restart
I had to do the same again and install: accelerate
Worked after the restart

**Comment by kijai** [comment]
Yeah this error is about old transformers version, I'm unsure what is the exact minimum version, but latest should work.
