### ISSUE TITLE
How do you use the SD3 model?

### ISSUE THREAD

**Issue by alex13by** [kijai/ComfyUI-LuminaWrapper#7]
Seeing support for the SD3 model, how do I use it?

**Comment by kijai** [comment]
I have not implemented that feature, and I'm unsure if it's even worth it when we already have good SD3 support in ComfyUI.

**Comment by alex13by** [comment]
The results of SD3 in comfyui are not satisfactory, and maybe a different implementation will have better results

**Comment by kijai** [comment]
> The results of SD3 in comfyui are not satisfactory, and maybe a different implementation will have better results

That has nothing to do with the Comfy implementation, it's the best one there is, the model itself is the problem.

**Comment by ikcikoR** [comment]
> The results of SD3 in comfyui are not satisfactory, and maybe a different implementation will have better results

1) You're making an issue on the wrong github repo, this is an extension for ComfyUI for Lumina models support, SD3 is supported by the main ComfyUI repo
2) ComfyUI repo isn't responsible for the quality either, Stability AI are the ones who messed up creating the model itself
