### ISSUE TITLE
Why can't the model reside in VRAM?

### ISSUE THREAD

**Issue by alex13by** [kijai/ComfyUI-LuminaWrapper#8]
I noticed that the video memory was emptied after each inference, and the time cost became larger

**Comment by kijai** [comment]
I never noticed any slowdown in models this size with my hardware, but of course you are right and that would be better without unnecessary offloading. I don't currently know how to use the comfy automatic model management with custom models like this, so I just added simple switch to the nodes to disable the offloading for now.
