### ISSUE TITLE
[BUG] OOM after update to keep models in VRAM (commit - d7fae402507256d58bac152c28436d1d35a8e018)

### ISSUE THREAD

**Issue by KreischerPanoptic** [kijai/ComfyUI-LuminaWrapper#9]
After commit - d7fae402507256d58bac152c28436d1d35a8e018, getting torch.cuda.OutOfMemoryError: Allocation on device constantly.

Behaviour on commit - c6bd70a75852f201cf8be2974b850f1be4bd30fe:
1. On first queuing on Comfy - OOM when trying to load Gemma-2b
2. On second queuing when Lumina-Next-SFT already loaded, it loads Gemma-2b without OOM

After commit - c6bd70a75852f201cf8be2974b850f1be4bd30fe:
1. Always OOM.

flash-attention is used.

**Comment by kijai** [comment]
Can you check if it's still an issue for you in the latest version?
